[auth]
providers = ["google"]
cookie_secret = "YVhpPK7IgCQ5Uec9yLMNpc71x/R5irCVCCilNBWMUsA="
redirect_uri = "http://localhost:8501/"

[auth.google]
client_id = "538242577437-bil3preod45viia8dva6e9nq1vqr6oae.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
